// Verbatim runtime prompts from RUNTIME-PROMPTS.txt. Fill {{PLACEHOLDERS}} with fill().
export const PROMPTS = {
 "WORDS_AND_RULES": "ALLOWED WORDS:\n{{ALLOWED}}\nNAMES:\n{{NAMES}}\n\nRULES FOR ALL CHINESE YOU WRITE\n- Simplified characters. Natural Mandarin that a native-speaking parent would really say.\n- Chinese is always an array of tokens, one per word: {\"w\": \"蛋糕\", \"p\": \"dan4 gao1\"}. Punctuation is {\"w\": \"。\"} with no \"p\".\n- Use only words from the ALLOWED WORDS and NAMES lists. Each token's \"w\" and \"p\" are copied exactly from one line of a list: the dictionary tones as listed, never changed for how they sound in speech (不 stays bu4 even before a fourth tone).\n- Use a word only in the sense given on its line. The same character with another reading or meaning is a different word (只 zhi1, the measure word, does not allow 只 zhi3 \"only\").\n- One list line is one token. Never join two listed words into one token. Putting listed words side by side is fine when the meaning is simply the two together (这 + 个, 吃 + 饭, 不 + 是). It is not allowed when together they make a different word that is not listed: having 东 and 西 does not allow 东西 \"thing\"; having 马 and 上 does not allow 马上 \"at once\".\n- A name is one token. No digits and no Latin letters inside Chinese.\n- Lead with the NEW words and reuse BRING IN words where they fit.\n- If the natural way to say something needs a word that is not listed, do not use it and do not write a clumsy sentence around it. Write something else, and report the word in the top-level \"needs\" array: {\"w\": \"<characters>\", \"why\": \"<a few English words>\"}. \"needs\" is [] when nothing was missing.\n- Everything that is not Chinese for the learner (descriptions, directions, ideas) is in English.\n- Return one JSON object and nothing else. No markdown fence, no commentary.",
 "source.read": "These photos are pages of a children's book, in reading order. Transcribe the printed story text of each page exactly as written. Do not translate, correct, summarise or complete it. Leave out page numbers, publisher details and writing that is part of a picture.\n\nWhere text is blurred, cut off or hidden, write [?] in place of the part you cannot read. Never guess.\n\nIf the book is in Chinese, transcribe the characters only and leave out any printed pinyin. If the book is in another language, transcribe it in that language.\n\nReturn one JSON object and nothing else:\n{\"language\": \"zh\" | \"en\" | \"other\",\n \"pages\": [{\"id\": \"p1\", \"text\": \"...\"}]}\nOne entry per photo, ids p1, p2, ... in the order given. A page with no story text has \"text\": \"\".",
 "source.words": "You are preparing a children's book for an adult who is learning Mandarin so they can read it aloud.\n\nBOOK LANGUAGE: {{LANGUAGE}}\nBOOK TEXT:\n{{PAGE_TEXT}}\n\nFIRST SPLIT INTO WORDS (made by a program, by longest dictionary match; it has mistakes):\n{{FIRST_SPLIT}}\n\nIf the book is Chinese: correct the split so each item is one word as a learner should learn it. Keep together what is one word with its own meaning (毛毛虫; 东西 \"thing\"; 马上 \"at once\"). Split what is simply two words side by side (不是 is 不 and 是; 这个 is 这 and 个; 吃饭 is 吃 and 饭). List every distinct word once. Give its pinyin and its meaning as it is used in this book. Ignore [?] marks and punctuation.\n\nIf the book is English: there is no split. List the Chinese word a Mandarin-speaking parent would use for each key thing, action and describing word in the story, 10 to 40 words, most important first, each with \"adapted\": true.\n\nAlso list companions: words that are not in your word list but that a listed word cannot be used naturally without, such as the measure word for a noun (只 for 猫). At most one companion per word, and only where it is really needed.\n\nPinyin is in tone numbers, one space between syllables, neutral tone 5, ü written u: (绿 is lu:4), dictionary tones.\n\nReturn one JSON object and nothing else:\n{\"words\": [{\"w\": \"毛毛虫\", \"p\": \"mao2 mao2 chong2\", \"meaning_en\": \"caterpillar\", \"count\": 7, \"adapted\": false}],\n \"companions\": [{\"w\": \"只\", \"p\": \"zhi1\", \"meaning_en\": \"measure word for animals\", \"with\": \"猫\"}]}\n\"count\" is how many times the word appears in the text (for an English book, how many times the thing it names appears). \"with\" is the characters of the listed word it accompanies.",
 "source.describe": "Write a short, original text in simple Mandarin for a parent to read aloud to a small child.\n\nTOPIC: {{TOPIC}}\nABOUT THE LEARNER: {{LEARNER_CONTEXT}}\n\n80 to 120 Chinese characters. Short sentences, everyday spoken words, the concrete things, actions and describing words this topic really needs, with some repetition as a picture book has. Simplified characters, no pinyin, no English. It must be your own text: never reproduce or closely retell a published book, even if the topic names one.\n\nReturn one JSON object and nothing else:\n{\"title_en\": \"...\", \"text\": \"...\"}",
 "lesson.sentences": "Write 8 example sentences that teach one Mandarin word to an adult beginner.\n\nTARGET WORD (allowed too): {{TARGET}}\n\n{{WORDS_AND_RULES}}\n\nEvery sentence contains the target word, in the sense given. Each is {{LENGTH}} characters long. Make the 8 different from each other: statements, questions, different people and things, and show the different ways the word is really used. Prefer the natural sentence: 我家有一只猫, not 我家有猫. If the natural sentence needs a companion word that is not listed (a measure word, for example), report it in \"needs\" and write a different sentence.\n\nFor each sentence give \"en\", natural English, and a gap for the quiz: \"gap\" is that same English with the target word's meaning replaced by ___ , and \"answers\" lists every English wording of the missing part that should be accepted, lower case. If the target is a particle (的 了 吗 呢 着 过 吧), a measure word or a name, it has no English of its own: give \"gap\": \"\" and \"answers\": [].\n\nReturn:\n{\"sentences\": [{\"tokens\": [...], \"en\": \"I like cake.\", \"gap\": \"I like ___.\", \"answers\": [\"cake\", \"cakes\"]}],\n \"needs\": []}\nExactly 8 sentences."
} as const;

export function fill(tpl: string, vars: Record<string, string>): string {
  return tpl.replace(/\{\{([A-Z_]+)\}\}/g, (m, k) => (k in vars ? vars[k] : m));
}
