/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ParkPreviewRouteImport } from './routes/park-preview'
import { Route as AuthenticatedDevRouteImport } from './routes/_authenticated/dev'
import { Route as AuthenticatedGymRouteImport } from './routes/_authenticated/gym'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedParkRouteImport } from './routes/_authenticated/park'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTownRouteImport } from './routes/_authenticated/town'
import { Route as AuthenticatedLessonLessonIdRouteImport } from './routes/_authenticated/lesson.$lessonId'
import { Route as AuthenticatedPlaceSlotRouteImport } from './routes/_authenticated/place.$slot'
import { Route as AuthenticatedReviewDirectionRouteImport } from './routes/_authenticated/review.$direction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkPreviewRoute = ParkPreviewRouteImport.update({
  id: '/park-preview',
  path: '/park-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDevRoute = AuthenticatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGymRoute = AuthenticatedGymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParkRoute = AuthenticatedParkRouteImport.update({
  id: '/park',
  path: '/park',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTownRoute = AuthenticatedTownRouteImport.update({
  id: '/town',
  path: '/town',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonLessonIdRoute =
  AuthenticatedLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaceSlotRoute = AuthenticatedPlaceSlotRouteImport.update({
  id: '/place/$slot',
  path: '/place/$slot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewDirectionRoute =
  AuthenticatedReviewDirectionRouteImport.update({
    id: '/review/$direction',
    path: '/review/$direction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/park-preview': typeof ParkPreviewRoute
  '/dev': typeof AuthenticatedDevRoute
  '/gym': typeof AuthenticatedGymRoute
  '/home': typeof AuthenticatedHomeRoute
  '/park': typeof AuthenticatedParkRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/town': typeof AuthenticatedTownRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/place/$slot': typeof AuthenticatedPlaceSlotRoute
  '/review/$direction': typeof AuthenticatedReviewDirectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/park-preview': typeof ParkPreviewRoute
  '/dev': typeof AuthenticatedDevRoute
  '/gym': typeof AuthenticatedGymRoute
  '/home': typeof AuthenticatedHomeRoute
  '/park': typeof AuthenticatedParkRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/town': typeof AuthenticatedTownRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/place/$slot': typeof AuthenticatedPlaceSlotRoute
  '/review/$direction': typeof AuthenticatedReviewDirectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/park-preview': typeof ParkPreviewRoute
  '/_authenticated/dev': typeof AuthenticatedDevRoute
  '/_authenticated/gym': typeof AuthenticatedGymRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/park': typeof AuthenticatedParkRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/town': typeof AuthenticatedTownRoute
  '/_authenticated/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/_authenticated/place/$slot': typeof AuthenticatedPlaceSlotRoute
  '/_authenticated/review/$direction': typeof AuthenticatedReviewDirectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/park-preview'
    | '/dev'
    | '/gym'
    | '/home'
    | '/park'
    | '/settings'
    | '/town'
    | '/lesson/$lessonId'
    | '/place/$slot'
    | '/review/$direction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/park-preview'
    | '/dev'
    | '/gym'
    | '/home'
    | '/park'
    | '/settings'
    | '/town'
    | '/lesson/$lessonId'
    | '/place/$slot'
    | '/review/$direction'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/park-preview'
    | '/_authenticated/dev'
    | '/_authenticated/gym'
    | '/_authenticated/home'
    | '/_authenticated/park'
    | '/_authenticated/settings'
    | '/_authenticated/town'
    | '/_authenticated/lesson/$lessonId'
    | '/_authenticated/place/$slot'
    | '/_authenticated/review/$direction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ParkPreviewRoute: typeof ParkPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/park-preview': {
      id: '/park-preview'
      path: '/park-preview'
      fullPath: '/park-preview'
      preLoaderRoute: typeof ParkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gym': {
      id: '/_authenticated/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof AuthenticatedGymRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/park': {
      id: '/_authenticated/park'
      path: '/park'
      fullPath: '/park'
      preLoaderRoute: typeof AuthenticatedParkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/town': {
      id: '/_authenticated/town'
      path: '/town'
      fullPath: '/town'
      preLoaderRoute: typeof AuthenticatedTownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson/$lessonId': {
      id: '/_authenticated/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/place/$slot': {
      id: '/_authenticated/place/$slot'
      path: '/place/$slot'
      fullPath: '/place/$slot'
      preLoaderRoute: typeof AuthenticatedPlaceSlotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$direction': {
      id: '/_authenticated/review/$direction'
      path: '/review/$direction'
      fullPath: '/review/$direction'
      preLoaderRoute: typeof AuthenticatedReviewDirectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDevRoute: typeof AuthenticatedDevRoute
  AuthenticatedGymRoute: typeof AuthenticatedGymRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedParkRoute: typeof AuthenticatedParkRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTownRoute: typeof AuthenticatedTownRoute
  AuthenticatedLessonLessonIdRoute: typeof AuthenticatedLessonLessonIdRoute
  AuthenticatedPlaceSlotRoute: typeof AuthenticatedPlaceSlotRoute
  AuthenticatedReviewDirectionRoute: typeof AuthenticatedReviewDirectionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDevRoute: AuthenticatedDevRoute,
  AuthenticatedGymRoute: AuthenticatedGymRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedParkRoute: AuthenticatedParkRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTownRoute: AuthenticatedTownRoute,
  AuthenticatedLessonLessonIdRoute: AuthenticatedLessonLessonIdRoute,
  AuthenticatedPlaceSlotRoute: AuthenticatedPlaceSlotRoute,
  AuthenticatedReviewDirectionRoute: AuthenticatedReviewDirectionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ParkPreviewRoute: ParkPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
